DNSZone:
    Type: AWS::Route53::HostedZone
    DependsOn: DNSLogGroupPolicy
    Properties:
        Name: !If [EnvironmentIsProd, !Sub "${self:custom.application}.omnilogistics.com", !Sub "${self:provider.stage}-${self:custom.application}.omnilogistics.com"]
        HostedZoneConfig:
            Comment: !Sub Delegated sub-domain for ${self:custom.application} in ${self:provider.stage}
        QueryLoggingConfig:
            CloudWatchLogsLogGroupArn: !GetAtt DNSLogGroup.Arn
        HostedZoneTags:
            - Key: Application
              Value: ${self:custom.application}
            - Key: DeployableUnitName
              Value: ${self:service}
            - Key: GitHubBranch
              Value: ${opt:GitHubBranch, 'default-branch'}
            - Key: Environment
              Value: ${self:provider.stage}
            - Key: Technical Contact
              Value: ${opt:TechnicalContact, "tgilbertson@omnilogistics.com"}

CleanupDNSZoneOnDeletion:
    Type: Custom::CleanupDNSZone
    Properties:
        ServiceToken: !ImportValue CleanupRoute53ZoneResourceArn
        HostedZoneId: !Ref DNSZone

SubDomainDelegation:
    Type: Custom::Route53CustomResource
    Properties:
        ServiceToken: !ImportValue UpdateRoute53ResourceArn
        Route53UpdaterRole:  "arn:aws:iam::332281781429:role/Cross-Account-Route53-CreateRoute53EntryRole-1MUPAJMHJP7LX"
        HostedZoneName: omnilogistics.com.
        Name: !If [EnvironmentIsProd, !Sub "${self:custom.application}.omnilogistics.com", !Sub "${self:provider.stage}-${self:custom.application}.omnilogistics.com"]
        Type: NS
        ResourceRecords: !GetAtt DNSZone.NameServers
        TTL: 300

ApiGatewayDNS:
    Type: AWS::Route53::RecordSet
    Properties:
        HostedZoneId: !Ref DNSZone
        Name: !If [EnvironmentIsProd, !Sub "${self:custom.application}.omnilogistics.com", !Sub "${self:provider.stage}-${self:custom.application}.omnilogistics.com"]
        Type: A
        AliasTarget:
            HostedZoneId: !GetAtt ApiGatewayDomainName.DistributionHostedZoneId
            DNSName: !GetAtt ApiGatewayDomainName.DistributionDomainName
            EvaluateTargetHealth: true

ApiGatewayDomainName:
    Type: AWS::ApiGateway::DomainName
    Properties:
        CertificateArn: !Ref ApiGatewayCertificate
        DomainName: !If [EnvironmentIsProd, !Sub "${self:custom.application}.omnilogistics.com", !Sub "${self:provider.stage}-${self:custom.application}.omnilogistics.com"]
        SecurityPolicy: TLS_1_2
        Tags:
            - Key: Application
              Value: ${self:service}
            - Key: DeployableUnitName
              Value: ${self:service}
            - Key: GitHubBranch
              Value: ${opt:GitHubBranch, 'default-branch'}
            - Key: Environment
              Value: ${self:provider.stage}
            - Key: Technical Contact
              Value: ${opt:TechnicalContact, "tgilbertson@omnilogistics.com"}

ApiGatewayCertificate:
    Type: AWS::CertificateManager::Certificate
    DependsOn: SubDomainDelegation
    Properties:
        DomainName: !If [EnvironmentIsProd, !Sub "${self:custom.application}.omnilogistics.com", !Sub "${self:provider.stage}-${self:custom.application}.omnilogistics.com"]
        DomainValidationOptions:
            - DomainName: !If [EnvironmentIsProd, !Sub "${self:custom.application}.omnilogistics.com", !Sub "${self:provider.stage}-${self:custom.application}.omnilogistics.com"]
              HostedZoneId: !Ref DNSZone
        ValidationMethod: DNS
        Tags:
            - Key: Application
              Value: ${self:custom.application}
            - Key: DeployableUnitName
              Value: ${self:service}
            - Key: GitHubBranch
              Value: ${opt:GitHubBranch, 'default-branch'}
            - Key: Environment
              Value: ${self:provider.stage}
            - Key: Technical Contact
              Value: ${opt:TechnicalContact, "tgilbertson@omnilogistics.com"}
